config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show

  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end

  def destroy

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Simple Airbnb</a>
      <div class="ms-auto flex">
         <a class="btn btn-outline-primary my-2 my-sm-0 ms-2" href="/flats/new">Add Flat</a>
      </div>
  </div>
</nav>

<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our flats (<%= @flats.count %>)</h1>
    </div>
  </div>
  <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-md-4">
          <div class="card m-2 bg-light">
            <img src="https://source.unsplash.com/random/500x250" class="card-img-top" alt="...">
            <div class="card-body">
              <h3 class="card-title"><%= flat.name %></h3>
              <p><%= flat.address %></p>
               <div class="flex">
                <div class="flex">
                <i class="material-icons me-2">people</i>
                <%= flat.number_of_guests %>
                </div>
                <div class="flex ms-3">
                <i class="material-icons me-2">euro_symbol</i>
                <%= flat.price_per_night %>
                </div>
               </div>
            </div>
            <div class="card-actions">
            <%= link_to 'More info', flat_path(flat) %>
            <%= link_to 'Edit', edit_flat_path(flat), class: 'ms-3 text-warning' %>
            <%= link_to 'Remove', flat_path(flat), method: :delete, class: 'ms-3 text-danger' %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>